# -*- coding: utf-8 -*-
"""embedding_preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4rXZKpKdfxTRNumUG9enOUNwDJu0_TK

## **NSMC data preprocessing**
"""

!git clone https://github.com/e9t/nsmc.git

import glob, json
import os, re

def process_nsmc(corpus_path, output_fname, process_json=True, with_label=True):
    if process_json:
        file_paths = glob.glob(corpus_path + "/*")
        with open(output_fname, 'w', encoding='utf-8') as f:
            for path in file_paths:
                contents = json.load(open(path))
                for content in contents:
                    sentence = content['review'].strip()
                    # 리뷰의 전체가 영어인 댓글이거나 내용이 없는 댓글은 제외
                    if re.search('[가-힣]', sentence):
                        score = '0' if int(content['rating'].strip()) < 6 else '1'
                        if len(sentence) > 0:
                            f.writelines(sentence + "\u241E" + content['movie_id'] + "\u241E" + score + "\n")
    else:
        with open(corpus_path, 'r', encoding='utf-8') as f1, \
                open(output_fname, 'w', encoding='utf-8') as f2:
            next(f1)  # skip head line
            for line in f1:
                _, sentence, label = line.strip().split('\t')
                if not sentence: continue
                if with_label:
                    f2.writelines(sentence + "\u241E" + label + "\n")
                else:
                    f2.writelines(sentence + "\n")

corpus_path = '/content/nsmc/raw'
out_f = 'processed_nsmc.txt'

process_nsmc(corpus_path, out_f, True, True)

"""## **korNLI data preprocessing**"""

!pip install Korpora

from Korpora import Korpora
Korpora.fetch("kornli")

kornli = Korpora.load("kornli")

kornli.multinli_train[0]

Korpora.fetch("korsts")
korsts = Korpora.load("korsts")

korsts.train[0]